title: Eddie Lee
description: Systems strategist & co-founder, Cloudfox Group Ltd
url: "https://cloudfoxit.github.io"
baseurl: "/eddielee"  # Ensure this matches your repository name
remote_theme: say8425/adam-blog-2
plugins:
  - jekyll-remote-theme
