title: Eddie Lee
description: Systems strategist & co-founder, Cloudfox Group Ltd
url: "https://cloudfoxit.github.io"
baseurl: "/eddielee"
author:
  name: Eddie Lee
  email: eddie@cloudfox.it
paginate: 5
paginate_path: "/page:num/"
permalink: /:title/
theme: null
